import { calculator } from './function/calculator.js';
import { clr } from './function/clear.js';
import { onClickNumber } from './function/onClickNumber.js';
import { operator } from './function/operator.js';
import { state } from './state/state.js';

document.querySelector('#num-1')!.addEventListener('click', onClickNumber);
document.querySelector('#num-2')!.addEventListener('click', onClickNumber);
document.querySelector('#num-3')!.addEventListener('click', onClickNumber);
document.querySelector('#num-4')!.addEventListener('click', onClickNumber);
document.querySelector('#num-5')!.addEventListener('click', onClickNumber);
document.querySelector('#num-6')!.addEventListener('click', onClickNumber);
document.querySelector('#num-7')!.addEventListener('click', onClickNumber);
document.querySelector('#num-8')!.addEventListener('click', onClickNumber);
document.querySelector('#num-9')!.addEventListener('click', onClickNumber);
document.querySelector('#num-0')!.addEventListener('click', onClickNumber);
document.querySelector('#plus')!.addEventListener('click', operator);
document.querySelector('#minus')!.addEventListener('click', operator);
document.querySelector('#divide')!.addEventListener('click', operator);
document.querySelector('#multiply')!.addEventListener('click', operator);
document.querySelector('#calculate')!.addEventListener('click', calculator);
document.querySelector('#clear')!.addEventListener('click', clr(state));
